name: Build And Test on GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# https://github.com/actions/runner-images/tree/main/images/macos
env:
  DEVELOPER_DIR: /Applications/Xcode_16.3.app/Contents/Developer

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
